<?php
/**
 * Forgot Password Page
 * User enters email, system sends OTP code via email
 */

session_start();

$message = '';
$messageType = '';

<<<<<<< Updated upstream
$DB_HOST = '127.0.0.1';
$DB_USER = 'root';
$DB_PASS = '';
$DB_NAME = 'Inventory_system_db';

$mysqli = @new mysqli($DB_HOST, $DB_USER, $DB_PASS, $DB_NAME);
if ($mysqli->connect_errno) {
    http_response_code(500);
    echo 'Database connection error.';
    exit;
}
$mysqli->set_charset('utf8mb4');

$method = $_SERVER['REQUEST_METHOD'] ?? 'GET';
$tokenRaw = trim((string)($_GET['token'] ?? $_POST['token'] ?? ''));

// Basic token sanity check (64 hex chars as generated by send_reset_email)
$validTokenFormat = preg_match('/^[0-9a-f]{64}$/i', $tokenRaw);

$errors = [];
$success = '';

if ($method === 'POST') {
    $pw = (string)($_POST['password'] ?? '');
    $pw2 = (string)($_POST['password_confirm'] ?? '');

    if (!$validTokenFormat) {
        $errors[] = 'Invalid or missing token.';
    }
    if (strlen($pw) < 8) {
        $errors[] = 'Password must be at least 8 characters.';
    }
    if ($pw !== $pw2) {
        $errors[] = 'Passwords do not match.';
    }

    if (empty($errors)) {
        $tokenHash = hash('sha256', $tokenRaw);

        // Find matching user with non-expired token
        $stmt = $mysqli->prepare('SELECT user_id FROM users WHERE password_reset_token = ? AND password_reset_expires >= NOW() AND status = "active" LIMIT 1');
        if ($stmt) {
            $stmt->bind_param('s', $tokenHash);
            $stmt->execute();
            $res = $stmt->get_result();
            $user = $res->fetch_assoc();
            $stmt->close();

            if ($user && isset($user['user_id'])) {
                $newHash = password_hash($pw, PASSWORD_DEFAULT);
                $upd = $mysqli->prepare('UPDATE users SET password = ?, password_reset_token = NULL, password_reset_expires = NULL, updated_at = CURRENT_TIMESTAMP WHERE user_id = ?');
                if ($upd) {
                    $upd->bind_param('si', $newHash, $user['user_id']);
                    if ($upd->execute()) {
                        $success = 'Your password has been updated. You may now <a href="login.php">log in</a>.';
                    } else {
                        $errors[] = 'Unable to update password. Try again later.';
                    }
                    $upd->close();
                } else {
                    $errors[] = 'Server error.';
                }
            } else {
                $errors[] = 'Invalid or expired token.';
            }
=======
// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $email = trim($_POST['email'] ?? '');
    
    // Validate email
    if (empty($email)) {
        $message = 'Please enter your email address.';
        $messageType = 'error';
    } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $message = 'Please enter a valid email address.';
        $messageType = 'error';
    } else {
        // Call send_otp.php API
        $url = 'http://' . $_SERVER['HTTP_HOST'] . '/pages/send_otp.php';
        
        // Use file_get_contents with stream context for POST request
        $postData = http_build_query(['email' => $email]);
        $context = stream_context_create([
            'http' => [
                'method' => 'POST',
                'header' => 'Content-Type: application/x-www-form-urlencoded',
                'content' => $postData
            ]
        ]);
        
        $response = @file_get_contents($url, false, $context);
        
        if ($response === false) {
            // Fallback to curl if file_get_contents fails
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, ['Content-Type: application/x-www-form-urlencoded']);
            $response = curl_exec($ch);
            curl_close($ch);
        }
        
        $result = json_decode($response, true);
        
        if ($result && isset($result['success']) && $result['success']) {
            // Redirect to verify OTP page
            $_SESSION['reset_email'] = $email;
                            header('Location: verify_otp.php?sent=1');
            exit;
>>>>>>> Stashed changes
        } else {
            $message = $result['error'] ?? 'Failed to send OTP. Please try again later.';
            $messageType = 'error';
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Forgot Password - Inventory System</title>
    <link rel="stylesheet" href="../css/main.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body class="min-h-screen bg-gradient-to-br from-primary-50 to-secondary-100 flex items-center justify-center p-4">
    <!-- Background Pattern -->
    <div class="absolute inset-0 opacity-10">
        <svg class="w-full h-full" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
            <defs>
                <pattern id="grid" width="10" height="10" patternUnits="userSpaceOnUse">
                    <path d="M 10 0 L 0 0 0 10" fill="none" stroke="currentColor" stroke-width="0.5"/>
                </pattern>
            </defs>
            <rect width="100%" height="100%" fill="url(#grid)" class="text-primary-300"/>
        </svg>
    </div>

    <!-- Main Container -->
    <div class="relative w-full max-w-md">
        <!-- Security Badge -->
        <div class="flex justify-center mb-6">
            <div class="flex items-center space-x-2 bg-white/80 backdrop-blur-sm px-4 py-2 rounded-full shadow-sm border border-border-light">
                <i class="fas fa-key text-success-600 text-sm"></i>
                <span class="text-xs font-medium text-text-secondary">Password Reset</span>
            </div>
        </div>

        <!-- Forgot Password Card -->
        <div class="bg-white/95 backdrop-blur-sm rounded-2xl shadow-xl border border-white/20 p-8 animation-slide-up">
            <!-- Logo and Header -->
            <div class="text-center mb-8">
                <div class="inline-flex items-center justify-center w-16 h-16 bg-primary-100 rounded-2xl mb-4">
                    <i class="fas fa-envelope text-primary-600 text-2xl"></i>
                </div>
                <h1 class="text-2xl font-semibold text-text-primary mb-2">Forgot Password?</h1>
                <p class="text-text-secondary">Enter your email to receive an OTP code</p>
            </div>

            <!-- Message Display -->
            <?php if ($message): ?>
                <div class="mb-6 p-4 rounded-xl <?php echo $messageType === 'success' ? 'bg-success-50 border border-success-200' : 'bg-error-50 border border-error-200'; ?>">
                    <div class="flex items-center">
                        <i class="fas <?php echo $messageType === 'success' ? 'fa-check-circle text-success-600' : 'fa-exclamation-circle text-error-600'; ?> mr-2"></i>
                        <span class="text-sm <?php echo $messageType === 'success' ? 'text-success-700' : 'text-error-700'; ?>"><?php echo htmlspecialchars($message); ?></span>
                    </div>
                    </div>
                <?php endif; ?>

            <!-- Form -->
            <form method="POST" class="space-y-6" novalidate>
                <!-- Email Field -->
                        <div class="space-y-2">
                    <label for="email" class="block text-sm font-medium text-text-primary">
                        Email Address
                            </label>
                            <div class="relative">
                                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                            <i class="fas fa-envelope text-text-tertiary text-sm"></i>
                                </div>
                        <input type="email" id="email" name="email" required autocomplete="email" 
                                       class="w-full pl-10 pr-4 py-3 border border-border-light rounded-xl focus:ring-2 focus:ring-primary-200 focus:border-primary-500 transition-all duration-200 bg-white/50" 
                               placeholder="Enter your email address"
                               value="<?php echo isset($_POST['email']) ? htmlspecialchars($_POST['email']) : ''; ?>">
                            </div>
                        </div>

                <!-- Submit Button -->
                        <button type="submit" class="w-full bg-primary hover:bg-primary-700 text-white font-medium py-3 px-4 rounded-xl transition-all duration-200 transform hover:scale-[1.02] focus:ring-2 focus:ring-primary-200 focus:ring-offset-2 shadow-lg">
                            <span class="flex items-center justify-center">
                        <i class="fas fa-paper-plane mr-2"></i>
                        Send OTP Code
                            </span>
                        </button>
                    </form>

            <!-- Back to Login -->
            <div class="mt-6 text-center">
                <a href="login.html" class="text-sm text-text-tertiary hover:text-text-secondary">
                    <i class="fas fa-arrow-left mr-1"></i>
                    Back to Login
                </a>
            </div>
        </div>

        <!-- Footer -->
        <div class="text-center mt-8">
            <p class="text-xs text-text-tertiary">
                © 2025 INVENTORY Management System. All Rights Reserved.
            </p>
        </div>
    </div>
</body>
</html>
